# Generated by Django 6.0.5 on 2026-06-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("envio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paquete",
            name="entregado",
            field=models.BooleanField(default=True),
        ),
    ]
