# Generated by Django 6.0.5 on 2026-06-02 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("envio", "0002_paquete_entregado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paquete",
            name="tipo",
        ),
    ]
