# Generated by Django 6.0.5 on 2026-06-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("envio", "0003_remove_paquete_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="paquete",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("fragil", "Fragil"),
                    ("refrigerado", "Refrigerado"),
                ],
                default="fragil",
                max_length=20,
            ),
        ),
    ]
